<a href="https://colab.research.google.com/github/suwutjaneet/Data_Viz/blob/main/More_advancted_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
ex_dict = {'a':10, '1':1, 'stat':5} 

In [4]:
ex_dict['stat']

5

In [6]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [7]:
ex2_dict[2]

'two'

In [10]:
ex2_dict[0] = 'zero'

In [11]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

In [12]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [13]:
for index in ex2_dict.keys():
  print(index)

1
2
3
0


In [14]:

ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [15]:

for values in ex2_dict.values():
  print(values)

one
two
three
zero


In [16]:
import numpy #เรียกใช้งาน package

In [20]:

ex2_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex2_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,2]

In [26]:
list_x = [[5.2,3.2,4.5],[9.1,0.1,0.3]] #การชี้ list
print(len(list_x)) #ดูว่ามีสมาชิกกี่ตัว
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


In [29]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex2_2d_array)

[[1 0 0]
 [0 0 1]]
[[1 0 0]
 [0 0 1]]


In [30]:
ex_2d_array + ex2_2d_array

NameError: ignored

In [31]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [32]:
ex2_2d_array * ex2_2d_array #การคูณแบบ array คือเอาตำแหน่งเดียวกันมาคูณกัน ต่างจาก การคูณ matrix

array([[1, 0, 0],
       [0, 0, 1]])

In [33]:
numpy.dot(ex2_2d_array, ex2_2d_array)

ValueError: ignored

# HW 5 เขียน function คูณ matrix
แล้ว test กับ matrix (2,3)(3,2) (4,4)(4,1) (2,2)*(2,2)

In [36]:
import numpy as np

In [37]:
# เมทริกซ์ (2,3)
mat1 = np.array([[2,3,4],[1,3,5]])
mat1

array([[2, 3, 4],
       [1, 3, 5]])

In [38]:
# เมทริกซ์(3,2)
mat2 = np.array([[1,2],[3,4],[5,6]])
mat2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
# เมทริกซ์(4,4)
mat3 = np.array([[1,3,5,7], [2,4,6,8], [2,4,4,2], [2,1,5,3]])
mat3

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [2, 4, 4, 2],
       [2, 1, 5, 3]])

In [41]:
# เมทริกซ์(4,1)
mat4 = np.array([[2], [4], [6], [8]])
mat4

array([[2],
       [4],
       [6],
       [8]])

In [42]:
# ดมทริกซ์(2,2)
mat5 = np.array([[2,4], [4,2]])
mat5

array([[2, 4],
       [4, 2]])

In [43]:
# เมทริกซ์(2,2)
mat6 = np.array([[6,3], [7,3]])
mat6

array([[6, 3],
       [7, 3]])

In [44]:
def mul_mat(a, b) :
  c = [[0 for row in range(len(b[0]))] for col in range(len(a))]
  for i in range(len(a)) :
    for j in range(len(b[0])) :
      for k in range(len(b)) :
        c[i][j] += a[i][k]*b[k][j]
  r = np.matrix(c)
  return r

In [45]:
mul_mat(mat1,mat2) #(2,3)*(3,2)

matrix([[31, 40],
        [35, 44]])

In [46]:
mul_mat(mat3,mat4) #(4,4)*(4,1)

matrix([[100],
        [120],
        [ 60],
        [ 62]])

In [47]:
mul_mat(mat5,mat6) #(2,2)*(2,2)

matrix([[40, 18],
        [38, 18]])

In [48]:
np.dot(mat1,mat2)

array([[31, 40],
       [35, 44]])