<a href="https://colab.research.google.com/github/suwutjaneet/Data_Viz/blob/main/More_advance_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

เรื่องที่เรียนไปแล้ว คือ list

## Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a':10,'1':1,'stat':5} #curly brackets ในการบอกว่ามันเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict= {1:'one',2:'two',3:'three'}

In [ ]:
ex2_dict[2]

'two'

### การเพิ่มสมาชิกใน dict

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

### คำสั่งใน dict

In [ ]:
ex2_dict.keys() #เป็นคำสั่งบอกว่าใน dict มีตัวอะไรบ้าง

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
  print(index)

1
2
3
0


In [ ]:
ex2_dict.values() #เป็นคำสั่งเอาไว้ print ค่าที่เป็นค่าของมันเอง

dict_values(['one', 'two', 'three', 'zero'])

dict เอาไปใช้ร่วมกับ Dataframe ของ pandas

# Numpy Array (array n มิติ)

numpy คือ package ที่ทำงานเกี่ยวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้)

numpy -> number python

In [ ]:
import numpy #วิธีเรียกใช้งาน package 

## สร้าง numpy array

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


### การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list

print(len(list_x))

print(list_x[1])

print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


### Operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #เป็นคำสั่งตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]

list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex_2d_array * ex2_2d_array #การคูณแบบ array คือ การเอาตำแหน่งเดียวกันมาคูณกัน (เอามาใช้ในการคูณ matix ไม่ได้)

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matix multiplication (dot product)

In [ ]:
numpy.dot(ex_2d_array,ex2_2d_array) #ที่ขึ้น error เพราะว่าการคูณ matix มีเงื่อนไข

ValueError: ignored

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T) #คำสั่ง .T คือ คำสั่ง transpost

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [ ]:
numpy.linalg.det(dot_mat)

-39.389999999999986

ถ้าอยากหาคำสั่งเอาไว้ใช้ให้ search google แล้วเปิดเว็บ stackoverflow หรือ เว็บของ package สำหรับ operations อื่นๆ

### matrix slicing

In [ ]:
print(ex_2d_array)



[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

### HW 5 เขียน function คูณ matrix แล้ว test กับ matrix ขนาด

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)
 

In [ ]:
import numpy as np

In [ ]:
A = np.array([[10,9,8],[7,6,5]]) #mattrix 2*3
B = np.array([[10,9],[8,7],[6,5]]) #mattrix 3*2
C = np.array([[20,19,18,17],[16,15,14,13],[12,11,10,9],[8,7,6,5]]) #mattrix 4*4
D = np.array([[7.2],[3.5],[8.4],[1.6]]) #mattrix 4*1
E = np.array([[2.9,6.3],[1.8,5.5]]) #mattrix 2*2
F = np.array([[11.4,2.0],[9.0,12.7]]) #mattrix 2*2

In [ ]:
print(f'A = {A}\n\n\
B = {B}\n\n\
C = {C}\n\n\
D = {D}\n\n\
E = {E}\n\n\
F = {F}\n')

A = [[10  9  8]
 [ 7  6  5]]

B = [[10  9]
 [ 8  7]
 [ 6  5]]

C = [[20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]]

D = [[7.2]
 [3.5]
 [8.4]
 [1.6]]

E = [[2.9 6.3]
 [1.8 5.5]]

F = [[11.4  2. ]
 [ 9.  12.7]]



In [ ]:
def matrixmult (A, B):
    Y = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                Y[i][j] += A[i][k]*B[k][j]
    X = np.matrix(Y)
    return X

## ข้อ 1

In [ ]:
matrixmult(A,B)

matrix([[220, 193],
        [148, 130]])

## ข้อ 2

In [ ]:
matrixmult(C,D)

matrix([[388.9],
        [306.1],
        [223.3],
        [140.5]])

## ข้อ 3

In [ ]:
matrixmult(E,F)

matrix([[89.76, 85.81],
        [70.02, 73.45]])

## zeros, ones, random

In [ ]:
import numpy as np #import numpy แล้วตั้งชื่อเป็น np << เวลาจะเรียกใช้ฟังก์ชันก็ใส่ np ไป

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### ones

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## เพิ่ม Matrix Operation (scalar multiplication) #scalar คือ ค่าคงที่1ค่าที่เป็นเลขตัวเดียว

In [ ]:
M_one = np.ones((2,3))

2*M_one

array([[2., 2., 2.],
       [2., 2., 2.]])

## random

In [ ]:
np.random.rand(3,2) #uniform random(0,1) คือ ค่า0-1ทุกตัวมีโอกาสโดนสุ่มมาเท่าๆกัน

array([[0.59440087, 0.24261483],
       [0.08420672, 0.28121186],
       [0.3491092 , 0.53099223]])

In [ ]:
np.random.randn(3,2) #sample  from normal distibution

array([[ 0.62318   , -1.26915805],
       [-0.07972369, -1.20369919],
       [-1.11005783, -0.42923046]])

In [ ]:
np.random.choice([1,2,3,'a','b','c']) #สุ่มค่าใน matrix ที่เราสร้างขึ้นมา 1 ตัว

'a'

In [ ]:
np.random.choice([1,2,3,28,11,100],size = 2) 

array([2, 3])

In [ ]:
np.random.choice([1,2,3,28,11,100],size = (2,3))

array([[11,  3,  3],
       [28, 28,  3]])

In [ ]:
np.random.choice([1,2,3,28,11,100],size = (2,3),replace=False)

array([[  3,  11,   1],
       [  2, 100,  28]])

In [ ]:
np.random.choice(['A','B','C','D','F'],size=35, p=[0.1,0.2,0.4,0.29,0.01])

array(['C', 'C', 'D', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'F', 'D', 'D',
       'C', 'C', 'D', 'C', 'C', 'D', 'C', 'B', 'D', 'D', 'D', 'A', 'D',
       'D', 'B', 'C', 'D', 'C', 'C', 'F', 'C', 'D'], dtype='<U1')

## เฉลย HW 5 (Matrix Multiplication)

In [ ]:
def mat_mul(A,B): # A เป็น matrix ตัวหน้า B เป็น matrix ตัวหลัง
    C = np.zeros((A.shape[0],B.shape[1])) # เตรียมขนาดของ matrix
    for r_a in range(A.shape[0]): # ไล่ไปตามแถวของตัวข้างหน้า
      for c_b in range(B.shape[1]): # ไล่ไปตามหลักของตัวข้างหลัง
        for every_element in range(A.shape[1]):
          C[r_a,c_b] = C[r_a,c_b] + A[r_a,every_element] * B[every_element,c_b]
    return C

In [ ]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8],[9,10],[11,12]])

In [ ]:
mat_mul(mat1,mat2)

array([[ 58.,  64.],
       [139., 154.]])